export const types = {
  SET_PARENT_ACCOUNTS_SUCCESS: "MAIN/SET_PARENT_ACCOUNTS_SUCCESS",
  SET_PARENT_ACCOUNTS_ERROR: "MAIN/SET_PARENT_ACCOUNTS_ERROR",
  SET_PARENT_ACCOUNT_SUCCESS: "MAIN/SET_PARENT_ACCOUNT_SUCCESS",
  SET_PARENT_ACCOUNT_ERROR: "MAIN/SET_PARENT_ACCOUNT_ERROR",
  ADD_PARENT_ACCOUNT_SUCCESS: "MAIN/ADD_PARENT_ACCOUNT_SUCCESS",
  ADD_PARENT_ACCOUNT_ERROR: "MAIN/ADD_PARENT_ACCOUNT_ERROR",
  UPDATE_PARENT_ACCOUNT_SUCCESS : "MAIN/UPDATE_PARENT_ACCOUNT_SUCCESS",
  UPDATE_PARENT_ACCOUNT_ERROR : "MAIN/UPDATE_PARENT_ACCOUNT_ERROR",
  DELETE_PARENT_ACCOUNT_SUCCESS : "MAIN/DELETE_PARENT_ACCOUNT_SUCCESS",
  DELETE_PARENT_ACCOUNT_ERROR : "MAIN/DELETE_PARENT_ACCOUNT_ERROR"
};