export const types = {
  SET_TRANSACTIONS_SUCCESS: "MAIN/SET_TRANSACTIONS_SUCCESS",
  SET_TRANSACTIONS_ERROR: "MAIN/SET_TRANSACTIONS_ERROR",
  SET_TRANSACTION_SUCCESS: "MAIN/SET_TRANSACTION_SUCCESS",
  SET_TRANSACTION_ERROR: "MAIN/SET_TRANSACTION_ERROR",
  ADD_TRANSACTION_SUCCESS: "MAIN/ADD_TRANSACTION_SUCCESS",
  ADD_TRANSACTION_ERROR: "MAIN/ADD_TRANSACTION_ERROR",
  UPDATE_TRANSACTION_SUCCESS : "MAIN/UPDATE_TRANSACTION_SUCCESS",
  UPDATE_TRANSACTION_ERROR : "MAIN/UPDATE_TRANSACTION_ERROR",
  DELETE_TRANSACTION_SUCCESS : "MAIN/DELETE_TRANSACTION_SUCCESS",
  DELETE_TRANSACTION_ERROR : "MAIN/DELETE_TRANSACTION_ERROR"
};