export const types = {
  SET_CHILDREN_ACCOUNTS_SUCCESS: "MAIN/SET_CHILDREN_ACCOUNTS_SUCCESS",
  SET_CHILDREN_ACCOUNTS_ERROR: "MAIN/SET_CHILDREN_ACCOUNTS_ERROR",
  SET_CHILDREN_ACCOUNT_SUCCESS: "MAIN/SET_CHILDREN_ACCOUNT_SUCCESS",
  SET_CHILDREN_ACCOUNT_ERROR: "MAIN/SET_CHILDREN_ACCOUNT_ERROR",
  ADD_CHILDREN_ACCOUNT_SUCCESS: "MAIN/ADD_CHILDREN_ACCOUNT_SUCCESS",
  ADD_CHILDREN_ACCOUNT_ERROR: "MAIN/ADD_CHILDREN_ACCOUNT_ERROR",
  UPDATE_CHILDREN_ACCOUNT_SUCCESS : "MAIN/UPDATE_CHILDREN_ACCOUNT_SUCCESS",
  UPDATE_CHILDREN_ACCOUNT_ERROR : "MAIN/UPDATE_CHILDREN_ACCOUNT_ERROR",
  DELETE_CHILDREN_ACCOUNT_SUCCESS : "MAIN/DELETE_CHILDREN_ACCOUNT_SUCCESS",
  DELETE_CHILDREN_ACCOUNT_ERROR : "MAIN/DELETE_CHILDREN_ACCOUNT_ERROR"
};